Repository retaildevcrews/helium, pull requests merged in 2020-06, with the labels that each got.

#433 Updated Release Template
  .github/ISSUE_TEMPLATE/release.md
Labels: Documentation, Helium, Release

#432 Updated CI-CD
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
  README.md
  docs/AppService.md
  docs/CI-CD/ACR.md
  docs/CI-CD/ACRTask.md
  docs/CI-CD/Docker.md
  docs/CI-CD/GithubActions.md
  docs/CI-CD/cicdWorkflow.yml
  docs/DotNet-Core-Developer.md
  docs/EngineeringPractices.md
  docs/aks/README.md
  docs/images/githubactions-acr-secrets.jpg
  docs/images/githubactions-docker-secrets.jpg
  docs/images/githubactions-run.jpg
  docs/images/githubactions-secret.jpg
  docs/index.md
Labels: Documentation, Helium

#431 Dashboard #398
  README.md
  docs/dashboard/Helium_Dashboard.json
  docs/dashboard/Helium_Dashboard_variables.json
Labels: Documentation, Helium, Pri1, size: M

#441 Updated docs
  .gitignore
  README.md
  docs/AppService.md
  docs/CodeSpaces.md
  docs/dashboard/Helium_Dashboard.json
  docs/dashboard/Helium_Dashboard_variables.json
  docs/images/codespaces1.JPG
  docs/images/codespaces2.JPG
  docs/images/codespaces3.JPG
  docs/images/codespaces4.JPG
  saveenv.sh
Labels: Helium

#455 Updated az acr commands
  README.md
Labels: Documentation, Helium

#457 Updating typescript dev docs
  docs/Typescript-Restify-Developer.md
Labels: Node

#458 Removing Key Rotation from TS/Java dev docs, fixing README images
  docs/Java-SpringBoot-Developer.md
  docs/Typescript-Restify-Developer.md
  docs/images/codespaces1.jpg
  docs/images/codespaces2.jpg
  docs/images/codespaces3.jpg
  docs/images/codespaces4.jpg
Labels: Documentation, Node
