Repository retaildevcrews/helium, pull requests merged in 2020-10, with the labels that each got.

#602 Update codespaces docs
  README.md
  docs/images/codespaces1.jpg
  docs/images/codespaces2.jpg
  docs/images/codespaces3.jpg
Labels: Documentation, Helium

#610 fixed dead links in DotNet-Core-Developer.md
  docs/DotNet-Core-Developer.md
Labels: Bug, Documentation

#613 Fixing 400 error resp link headers
  TestFiles/bad.json
  TestFiles/baseline.json
  TestFiles/e2e.json
  docs/HttpErrorResponses.md
  docs/ParameterValidation.md
Labels: Documentation
