Repository retaildevcrews/helium, pull requests merged in 2020-02, with the labels that each got.

#213 Created Retro Template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Helium, Pri1

#228 Update Task github template
  .github/ISSUE_TEMPLATE/task.md
Labels: Helium

#233 Design Review - Added Task to checklist
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Documentation, Pri1

#242 Updated Design Review template
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Documentation, Helium

#246 Template for Comparison Review
  .github/ISSUE_TEMPLATE/comparison.md
Labels: Documentation, Helium, Pri1, Sharing, size: S

#261 parameter validations
  docs/ParameterValidation.md
Labels: C#, Design Review, Documentation, Java, Node

#262 Updated Standard Templates (Bug, Task, Release, DoD, Feature)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/comparison.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Documentation, Helium, Pri1

#264 Param validation
  docs/ParameterValidation.md
Labels: Bug, Documentation, Helium
