Repository retaildevcrews/helium, pull requests merged in 2020-01, with the labels that each got.

#92 Healthz updates
  src/Program.cs
  src/Smoker/Model.cs
  src/Smoker/SmokeTest.cs
  src/TestFiles/baseline.json
Labels: Helium

#95 Helium Logger updates
  src/Smoker/SmokeTest.cs
  src/TestFiles/README.md
  src/TestFiles/baseline.json
  src/TestFiles/dotnet.json
Labels: C#

#96 make aad-podid.sh more user freindly
  docs/aks/README.md
  docs/aks/aad-podid.sh
  docs/aks/cluster/charts/helium/Chart.yaml
  docs/aks/cluster/charts/helium/helm-config.yaml
  saveenv.sh
Labels: Enhancement, Helium, size: S

#94 Updated README.md CosmosDB database and collection creation lines
  README.md
Labels: Helium

#98 automate the replacement of values in AKS_Dashboard.json file
  docs/aks/README.md
  docs/aks/cluster/charts/helium/Chart.yaml
  docs/aks/demo/AKS_Dashboard.json
Labels: Documentation, Enhancement, Helium, size: S

#104 Data birth year
  src/TestFiles/actorById.json
Labels: Bug, Helium

#113 Issue#83
  src/Program.cs
  src/Smoker/SmokeTest.cs
  src/TestFiles/Samples/java.json
  src/TestFiles/java.json
Labels: Enhancement, Helium, size: S

#115 Healthz statuscode
  src/TestFiles/baseline.json
  src/TestFiles/msft.json
Labels: Helium

#118 Created DoD standard template
  .github/ISSUE_TEMPLATE/user-story--dod-review.md
Labels: Documentation, Pri2

#121 Created Task Template with DoD Checklist
  .github/ISSUE_TEMPLATE/tasks.md
  .github/ISSUE_TEMPLATE/user-story--dod-review.md
Labels: Documentation, Pri2, size: S

#124 Update java.json
  src/TestFiles/java.json
Labels: Bug, Helium, Java, Pri1, size: S

#131 Added "Release" tag for DoD Review template
  .github/ISSUE_TEMPLATE/user-story--dod-review.md
Labels: Release

#136 updated CI-CD
  .github/workflows/dockerCI.yml
Labels: Helium

#148 Updated baseline.json validation test
  src/TestFiles/baseline.json
Labels: Helium

#149 Added release template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/tasks.md
  .github/ISSUE_TEMPLATE/user-story.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Helium, Release

#137 Logging update
  src/Smoker/SmokeTest.cs
Labels: Helium

#155 Release template
  .github/ISSUE_TEMPLATE/survey.md
Labels: Documentation, Helium

#162 Added PerfTarget data to json
  src/TestFiles/actorById.json
  src/TestFiles/baseline.json
  src/TestFiles/dotnet.json
  src/TestFiles/featured.json
  src/TestFiles/genres.json
  src/TestFiles/java.json
  src/TestFiles/movieById.json
  src/TestFiles/moviesByActorId.json
  src/TestFiles/node.json
  src/TestFiles/perfTargets.json
  src/TestFiles/rating.json
  src/TestFiles/search.json
  src/TestFiles/year.json
Labels: Helium

#163 Perf metrics tracking
  src/Metrics.cs
  src/Middleware/indexHandler.cs
  src/Smoker/Model.cs
  src/Smoker/SmokeTest.cs
Labels: Helium

#164 Added Perf tracking
  src/Smoker/SmokeTest.cs
Labels: Helium

#169 updated json test file
  src/TestFiles/movieById.json
Labels: Helium

#173 Updated DoD per team agreement
  docs/EngineeringPractices.md
Labels: Documentation, Pri1, Release

#174 Updated DoD
  docs/EngineeringPractices.md
Labels: Documentation, Pri1

#182 Remove source code
  .dockerignore
  .github/workflows/dockerCI.yml
  CHANGELOG.md
  Dockerfile
  README.md
  helium.sln
  src/GlobalSuppressions.cs
  src/Metrics.cs
  src/Middleware/indexHandler.cs
  src/Middleware/requestLogger.cs
  src/Middleware/robotsText.cs
  src/Middleware/version.cs
  src/Program.cs
  src/Smoker/Model.cs
  src/Smoker/SmokeTest.cs
  src/Startup.cs
  src/TaskRunner.cs
  src/TestFiles/actorById.json
  src/TestFiles/baseline.json
  src/TestFiles/benchmark.json
  src/TestFiles/dotnet.json
  src/TestFiles/featured.json
  src/TestFiles/genres.json
  src/TestFiles/java.json
  src/TestFiles/movieById.json
  src/TestFiles/moviesByActorId.json
  src/TestFiles/msft.json
  src/TestFiles/node.json
  src/TestFiles/perfTargets.json
  src/TestFiles/rating.json
  src/TestFiles/search.json
  src/TestFiles/year.json
  src/Version.cs
  src/appsettings.Development.json
  src/appsettings.json
  src/config.cs
  src/integration-test.csproj
Labels: Helium

#188 Adding checkpoint template per guidelines
  .github/ISSUE_TEMPLATE/checkpoint.md
Labels: CP Review, Pri1, Sharing

#190 Design Review Issue Template
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Documentation, Helium, Pri1

#189 CP Review template updated
  .github/ISSUE_TEMPLATE/checkpoint.md
Labels: CP Review, Pri1, Sharing, size: S

#196 Updated to add Kanban best practices
  docs/EngineeringPractices.md
Labels: Documentation, Pri1, Sharing, size: S

#201 Update EngineeringPractices.md
  docs/EngineeringPractices.md
Labels: Documentation, Pri1, Sharing, size: S
