Repository retaildevcrews/helium, pull requests merged in 2020-07, with the labels that each got.

#460 Anflinch/aksdocs
  docs/aks/README.md
  docs/aks/cluster/charts/helium/helm-config.yaml
  docs/aks/cluster/charts/helium/templates/heliumcs-deploy.yaml
  saveenv.sh
Labels: Helium

#475 Scope the SP on creation
  README.md
Labels: Helium

#476 Moving He_ACR_Id command up in Readme
  README.md
Labels: Helium

#471 Webv
  README.md
  docs/LanguageComparison.md
Labels: WebV

#477 Updating dashboard setup docs
  README.md
Labels: Documentation

#454 adding Observability visio
  README.md
  docs/images/dashboard.jpg
Labels: Documentation, Pri1, size: S

#478 updated docs
  README.md
Labels: Documentation, Helium

#481 Adding Log Analytics query examples
  README.md
  docs/AppService.md
Labels: Documentation, Helium

#484 Syncing differences between startup doc and terraform setup
  README.md
Labels: Documentation, Helium

#486 Updating AppService temp image
  docs/AppService.md
Labels: Documentation, Helium

#485 Moving smoketests docs
  README.md
  docs/AppService.md
Labels: Documentation, Helium
