Repository retaildevcrews/helium, pull requests merged in 2020-09, with the labels that each got.

#545 issue #540 Fix AKS pod identity installation by using helm chart
  docs/aks/README.md
  docs/aks/aad-podid.sh
Labels: Documentation, Helium, customer feedback

#544 Http error response design guide
  docs/HttpErrorResponses.md
  docs/ParameterValidation.md
Labels: Documentation

#554 Updated dead links
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/workflows/mdlinkcheck.yml
  docs/CI-CD/GitHubActions.md
  docs/DotNet-Core-Developer.md
  docs/EngineeringPractices.md
  docs/index.md
  mlc_config.json
Labels: Bug, Documentation

#558 Update checkpoint.md
  .github/ISSUE_TEMPLATE/checkpoint.md
Labels: Documentation

#559 Added scheduled link checker for markdown files
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, Documentation

#565 Updated docs from CPR feedback
  .github/ISSUE_TEMPLATE/release.md
  docs/EngineeringPractices.md
Labels: Helium

#561 Update ParameterValidation documentation to align with design specification
  docs/ParameterValidation.md
Labels: Documentation, Helium, Pri1, size: S

#572 Added instructions for App Service dotnetcore (without containers)
  README.md
  docs/AppService-dotnetcore.md
  docs/AppService.md
  docs/AppServiceObservability.md
Labels: CustomerFeedback, Helium

#582 Visual Studio Code Cleanup Documentation
  docs/EngineeringPractices.md
  docs/images/vs2019-code-cleanup.png
Labels: Documentation, Helium, Pri1, size: S

#583 Modify AKS Readme setup to work with terraform created cluster
  docs/aks/README.md
  docs/aks/aad-podid.sh
Labels: Helium

#584 issue #541 replace deprecated ingress helm chart with app gateway ingress
  docs/AppServiceObservability.md
  docs/aks/README.md
  docs/aks/aad-podid.sh
  docs/aks/cluster/charts/helium/templates/heliumcs-ingress.yaml
  docs/aks/cluster/charts/helium/values.yaml
  docs/aks/cluster/manifests/ingress-nginx-namespace.yaml
Labels: DevExperience, Documentation

#597 Updated scheduled link check to create project cards
  .github/workflows/scheduled_mdlinkcheck.yml
  docs/DotNet-Core-Developer.md
Labels: Bug, Documentation, Pri1
