Repository retaildevcrews/helium, pull requests merged in 2020-08, with the labels that each got.

#502 Fix smoker containers startup commands
  docs/AppService.md
Labels: Documentation, Helium

#515 Removing query to calculate percentile
  docs/AppService.md
Labels: Documentation, Helium

#496 Sync dev docs
  docs/DotNet-Core-Developer.md
  docs/Java-Spring-WebFlux-Developer.md
  docs/Java-SpringBoot-Developer.md
  docs/Typescript-Restify-Developer.md
  docs/images/cosmosdb-flux.png
Labels: Documentation

#524 Updated docs per Teams discussion
  docs/EngineeringPractices.md
Labels: Helium

#527 issue #523 Update documentation for keyvault and soft delete
  README.md
Labels: Documentation, Helium

#528 issue #522 Add a note about the environment variables that intentionally save commands as strings
  README.md
Labels: Documentation

#536 Modify webv aci
  docs/AppService.md
Labels: Documentation

#534 Note about SP creation
  README.md
  docs/Java-Spring-WebFlux-Developer.md
Labels: Documentation, Helium

#539 Updating Partition Key documentation based on recent refactor
  docs/DotNet-Core-Developer.md
  docs/Java-Spring-WebFlux-Developer.md
  docs/Typescript-Restify-Developer.md
Labels: Documentation
