Repository retaildevcrews/helium, pull requests merged in 2020-04, with the labels that each got.

#335 Working Agreement
  docs/WorkingAgreement.md
Labels: Documentation, Helium

#351 Create typescript dev docs and other doc updates
  docs/AlertSetup.md
  docs/Typescript-Restify-Developer.md
Labels: Helium, Node

#352 add workflow for issue triage and PR submitted automation
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
Labels: Helium, Pri1, size: S

#359 Update TS and C# dev docs and other doc updates as needed
  docs/AlertSetup.md
  docs/CSharp-ASPDotNet-Developer.md
  docs/Typescript-Restify-Developer.md
Labels: C#, Documentation, Helium, Node

#367 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation
