Repository retaildevcrews/helium, pull requests merged in 2020-05, with the labels that each got.

#388 Swagger update
  swagger/helium-dotnet.json
  swagger/helium.json
Labels: C#

#404 Updated Survey with new questions
  .github/ISSUE_TEMPLATE/survey.md
Labels: Documentation, Retro

#410 Updating MIKV section in Language Comparison Doc
  docs/LanguageComparison.md
Labels: Documentation, Helium
